config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :controllers => { registrations: 'users/registrations' }
  resources :candidates
  resources :voters
  resources :users
  resources :elections

  root 'elections#index'

  resources :elections do
    member do
      get :toggle_election_statut
      get :delete_vote
      get :end_election
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/voter.rb
class Voter < ApplicationRecord
  belongs_to :election
  belongs_to :user

  def num_of_vote_current_user(election, vote)
    num = Voter.where(election_id: election.id, user_id: vote.user_id ).count
  end

end

app/controllers/voters_controller.rb
class VotersController < ApplicationController
  before_action :set_voter, only: %i[ show edit update destroy ]

  # GET /voters or /voters.json
  def index
    @voters = Voter.all
  end

  # GET /voters/1 or /voters/1.json
  def show
  end

  # GET /voters/new
  def new
    @election_id = params[:election]

    if Voter.where(election_id: @election_id, user_id: current_user.id ).count >= 2
        redirect_to election_path(@election_id), notice: "vous avez déjà voté"
    else
        @voter = Voter.new
        @voter.election_id = @election_id
        @voter.user_id = current_user.id
        @voter.save
        redirect_to edit_voter_path(@voter)
    end
  end

  # GET /voters/1/edit
  def edit
  end

  # POST /voters or /voters.json
  def create
    @voter = Voter.new(voter_params)

    
    if @voter.save

        if @voter.candidate_id.blank?
            @voter.destroy
        end

        redirect_to @voter, notice: "Voter was successfully created." 
    else
        render :new, status: :unprocessable_entity 
    end
    
  end

  # PATCH/PUT /voters/1 or /voters/1.json
  def update

      if @voter.update(voter_params)
        redirect_to election_path(@voter.election_id), notice: "Voter was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
  end

  # DELETE /voters/1 or /voters/1.json
  def destroy
    @voter.destroy
    redirect_to election_path(@voter.election_id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voter
      @voter = Voter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def voter_params
      params.require(:voter).permit(:election_id, :user_id, :candidate_id)
    end
end

app/helpers/voters_helper.rb
module VotersHelper
end

app/views/voters/_form.html.erb
<%= form_with(model: voter) do |form| %>
  <% if voter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(voter.errors.count, "error") %> prohibited this voter from being saved:</h2>

      <ul>
        <% voter.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :election_id, value: @voter.election_id %>
  <%= form.hidden_field :user_id, value: @voter.user_id %>

  <h4><%= current_user.first_name.capitalize %> c'est a toi de voter pour l'élection : </h4>
  <p>merci de choisir un candidat dans la liste :</p>

   <div class="field">
    <%= form.select :candidate_id, options_for_select(Candidate.where(election_id: @voter.election_id).collect {|candidate| ["#{candidate.user.first_name} #{candidate.user.last_name}", candidate.id] }), :include_blank => 'Choississez un candidat :', :input_html => { :class => 'form-control' }, :style => '', required: true  %>
  </div>

  <div class="actions">
    <%= form.submit 'A voté', class: 'btn btn-primary mt-2 mb-2' %>
  </div>
<% end %>

<%= link_to 'Annuler', voter, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>

app/views/voters/edit.html.erb
<h1>A toi de voter</h1>

<%= render 'form', voter: @voter %>

app/views/voters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Voters</h1>

<table>
  <thead>
    <tr>
      <th>Election</th>
      <th>User</th>
      <th>Candidate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @voters.each do |voter| %>
      <tr>
        <td><%= voter.election_id %></td>
        <td><%= voter.user_id %></td>
        <td><%= voter.candidate_id %></td>
        <td><%= link_to 'Show', voter %></td>
        <td><%= link_to 'Edit', edit_voter_path(voter) %></td>
        <td><%= link_to 'Destroy', voter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Voter', new_voter_path %>

app/views/voters/new.html.erb
<h1>New Voter</h1>

<%= render 'form', voter: @voter %>

<%= link_to 'Back', voters_path %>

app/views/voters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Election:</strong>
  <%= @voter.election_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @voter.user_id %>
</p>

<%= link_to 'Edit', edit_voter_path(@voter) %> |
<%= link_to 'Back', voters_path %>
<%= link_to 'Destroy', voter, method: :delete, data: { confirm: 'Are you sure?' } %>