config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :controllers => { registrations: 'users/registrations' }
  resources :candidates
  resources :voters
  resources :users
  resources :elections

  root 'elections#index'

  resources :elections do
    member do
      get :toggle_election_statut
      get :delete_vote
      get :end_election
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  belongs_to :election
  belongs_to :user
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: %i[ show edit update destroy ]

  # GET /candidates or /candidates.json
  def index
    @candidates = Candidate.all
  end

  # GET /candidates/1 or /candidates/1.json
  def show
  end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
    @election_id = params[:election]
  end

  # GET /candidates/1/edit
  def edit
  end

  # POST /candidates or /candidates.json
  def create

    @candidate = Candidate.new(candidate_params)
    
    if @candidate.save
        
        @candidate_declared = Candidate.where(election_id: @candidate.election_id, user_id: @candidate.user_id).count
        
        if @candidate.user_id.blank?
            @candidate.destroy
            redirect_to election_path(@candidate.election_id)
        end

        if  @candidate_declared > 1
            @candidate.destroy
            redirect_to election_path(@candidate.election_id), notice: "CE CANDIDAT EST DEJA DECLARE - IMPOSSIBLE DE LE DECLARER A NOUVEAU"
        else 
            redirect_to election_path(@candidate.election_id), notice: "Candidate was successfully created."
        end
    else
        redirect_to election_path(@candidate.election_id)
    end
    
  end

  # PATCH/PUT /candidates/1 or /candidates/1.json
  def update
    respond_to do |format|
      if @candidate.update(candidate_params)
        format.html { redirect_to @candidate, notice: "Candidate was successfully updated." }
        format.json { render :show, status: :ok, location: @candidate }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1 or /candidates/1.json
  def destroy
    @candidate.destroy
    respond_to do |format|
      format.html { redirect_to candidates_url, notice: "Candidate was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def candidate_params
      params.require(:candidate).permit(:election_id, :user_id, :slogan, :program)
    end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.erb
<%= form_with(model: candidate) do |form| %>
  <% if candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
        <% candidate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :election_id, :value => @election_id %>


  <div class="field">
    <p>Choissisez le candidats dans la liste : </p>
    <%= form.select :user_id, options_for_select(User.all.collect {|user| ["#{user.first_name} #{user.last_name}", user.id] }), :include_blank => 'Choississez un candidat :', :input_html => { :class => 'form-control' }, :style => '', required: true  %>
  </div>

  <div class="field mt-4 mb-3">
    <%= form.label :slogan %><br>
    <%= form.text_area :slogan %>
  </div>

  <div class="actions">
    <%= form.submit 'Valider la candidature', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<h1>Editing Candidate</h1>

<%= render 'form', candidate: @candidate %>

<%= link_to 'Show', @candidate %> |
<%= link_to 'Back', candidates_path %>

app/views/candidates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Candidates</h1>

<table>
  <thead>
    <tr>
      <th>Election</th>
      <th>User</th>
      <th>Slogan</th>
      <th>Program</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= candidate.election_id %></td>
        <td><%= candidate.user_id %></td>
        <td><%= candidate.slogan %></td>
        <td><%= candidate.program %></td>
        <td><%= link_to 'Show', candidate %></td>
        <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
        <td><%= link_to 'Destroy', candidate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Candidate', new_candidate_path %>

app/views/candidates/new.html.erb
<h1>Nouveau Candidat</h1>

<%= render 'form', candidate: @candidate %>

<%= link_to 'Annuler', election_path(@election_id), class: 'btn btn-danger mt-3' %>

app/views/candidates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Election:</strong>
  <%= @candidate.election_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @candidate.user_id %>
</p>

<p>
  <strong>Slogan:</strong>
  <%= @candidate.slogan %>
</p>

<p>
  <strong>Program:</strong>
  <%= @candidate.program %>
</p>

<%= link_to 'Edit', edit_candidate_path(@candidate) %> |
<%= link_to 'Back', candidates_path %>